In [30]:
import numpy as np

RI = [0, 0, 0.58, 0.90, 1.12, 1.24, 1.32, 1.41, 1.45, 1.49]

In [42]:
A = [
    [1, 3, 2, 5],
    [1/3, 1, 1/2, 3],
    [1/2, 2, 1, 4],
    [1/5, 1/3, 1/4, 1],
]
# Step 1.
M = np.multiply.reduce(A,axis=1)

# Step 2.
n = np.shape(M)[0]
W_AVG = pow(M, 1/n)

# Step 3.
W_A = W_AVG / np.sum(W_AVG)

# Step 4.
lamda_max = (1/n) * np.sum( (np.matmul(A, W_A) ) / W_A)
CI = (lamda_max - n) / (n - 1)
CR = CI / RI[n - 1]

print(W_A)
print(CR < 0.1)

#print(CR)
#print(CI)
#print(RI[n-1])

[0.47234309 0.16971481 0.28542516 0.07251694]
True


In [43]:
# B1 -- C
B = [
    [1, 2, 3, 4],
    [1/2, 1, 2, 3],
    [1/3, 1/2, 1, 2],
    [1/4, 1/3, 1/2, 1],
]
# Step 1.
M = np.multiply.reduce(B,axis=1)

# Step 2.
n = np.shape(M)[0]
W_AVG = pow(M, 1/n)

# Step 3.
W_B1 = W_AVG / np.sum(W_AVG)

# Step 4.
lamda_max = (1/n) * np.sum( (np.matmul(B, W_B1) ) / W_B1)
CI = (lamda_max - n) / (n - 1)
CR = CI / RI[n - 1]

print(W_B1)
print(CR < 0.1)

[0.46684856 0.27758982 0.16026656 0.09529506]
True


In [44]:
# B2 -- C
B = [
    [1, 2, 2],
    [1/2, 1, 1],
    [1/2, 1, 1],
]
# Step 1.
M = np.multiply.reduce(B,axis=1)

# Step 2.
n = np.shape(M)[0]
W_AVG = pow(M, 1/n)

# Step 3.
W_B2 = W_AVG / np.sum(W_AVG)

# Step 4.
lamda_max = (1/n) * np.sum( (np.matmul(B, W_B2) ) / W_B2)
CI = (lamda_max - n) / (n - 1)
CR = CI / RI[n - 1]

print(W_B2)
print(CR < 0.1)

[0.5  0.25 0.25]
True


In [46]:
# B3 -- C
B = [
    [1, 1/3, 1/4],
    [3, 1, 1/2],
    [4, 2, 1],
]
# Step 1.
M = np.multiply.reduce(B,axis=1)

# Step 2.
n = np.shape(M)[0]
W_AVG = pow(M, 1/n)

# Step 3.
W_B3 = W_AVG / np.sum(W_AVG)

# Step 4.
lamda_max = (1/n) * np.sum( (np.matmul(B, W_B3) ) / W_B3)
CI = (lamda_max - n) / (n - 1)
CR = CI / RI[n - 1]

print(W_B3)
print(CR < 0.1)

[0.12195719 0.31961826 0.55842454]
True


In [47]:
# B4 -- C
B = [
    [1, 2, 3],
    [1/2, 1, 2],
    [1/3, 1/2, 1],
]
# Step 1.
M = np.multiply.reduce(B,axis=1)

# Step 2.
n = np.shape(M)[0]
W_AVG = pow(M, 1/n)

# Step 3.
W_B4 = W_AVG / np.sum(W_AVG)

# Step 4.
lamda_max = (1/n) * np.sum( (np.matmul(B, W_B4) ) / W_B4)
CI = (lamda_max - n) / (n - 1)
CR = CI / RI[n - 1]

print(W_B4)
print(CR < 0.1)

[0.53961455 0.29696133 0.16342412]
True


In [50]:
print(W_A[0] * W_B1)
print(W_A[1] * W_B2)
print(W_A[2] * W_B3)
print(W_A[3] * W_B4)

[0.22051269 0.13111763 0.0757008  0.04501197]
[0.08485741 0.0424287  0.0424287 ]
[0.03480965 0.09122709 0.15938841]
[0.03913119 0.02153473 0.01185102]
