In [18]:
import numpy as np

RI = [0, 0, 0.58, 0.90, 1.12, 1.24, 1.32, 1.41, 1.45, 1.49]

In [27]:
#A = [
#    [1, 3, 2, 5],
#    [1/3, 1, 1/2, 3],
#    [1/2, 2, 1, 4],
#    [1/5, 1/3, 1/4, 1],
#]
A = [
    [1, 2, 3, 3],
    [1/2, 1, 2, 3],
    [1/3, 1/2, 1, 2],
    [1/3, 1/3, 1/2, 1],
]
# Step 1.
M = np.multiply.reduce(A,axis=1)

# Step 2.
n = np.shape(M)[0]
W_AVG = pow(M, 1/n)

# Step 3.
W_A = W_AVG / np.sum(W_AVG)

# Step 4.
lamda_max = (1/n) * np.sum( (np.matmul(A, W_A) ) / W_A)
CI = (lamda_max - n) / (n - 1)
CR = CI / RI[n - 1]

print(W_A)
print(CR < 0.1)

print("CR:", CR)
print("lamda_max:", lamda_max)
print("CI:", CI)
#print(RI[n-1])

[0.4457243  0.28479247 0.16442501 0.10505822]
True
CR: 0.026247326796485657
lamda_max: 4.070867782350511
CI: 0.023622594116837092


In [20]:
# B1 -- C
#B = [
#    [1, 2, 3, 4],
#    [1/2, 1, 2, 3],
#    [1/3, 1/2, 1, 2],
#    [1/4, 1/3, 1/2, 1],
#]

B = [
    [1, 3, 2, 5, 4],
    [1/3, 1, 1/2, 4, 3],
    [1/2, 2, 1, 5, 2],
    [1/5, 1/4, 1/5, 1, 1/2],
    [1/4, 1/3, 1/2, 2, 1],
]

# Step 1.
M = np.multiply.reduce(B,axis=1)

# Step 2.
n = np.shape(M)[0]
W_AVG = pow(M, 1/n)

# Step 3.
W_B1 = W_AVG / np.sum(W_AVG)

# Step 4.
lamda_max = (1/n) * np.sum( (np.matmul(B, W_B1) ) / W_B1)
CI = (lamda_max - n) / (n - 1)
CR = CI / RI[n - 1]

print(W_B1)
print(CR < 0.1)
print("CR:", CR)

[0.41393319 0.18251561 0.25182219 0.05506657 0.09666244]
True
CR: 0.03477613675121061


In [21]:
# B2 -- C
#B = [
#    [1, 2, 2],
#    [1/2, 1, 1],
#    [1/2, 1, 1],
#]

B = [
    [1, 2, 5, 4],
    [1/2, 1, 4, 3],
    [1/5, 1/4, 1, 1/2],
    [1/4, 1/3, 2, 1],
]

# Step 1.
M = np.multiply.reduce(B,axis=1)

# Step 2.
n = np.shape(M)[0]
W_AVG = pow(M, 1/n)

# Step 3.
W_B2 = W_AVG / np.sum(W_AVG)

# Step 4.
lamda_max = (1/n) * np.sum( (np.matmul(B, W_B2) ) / W_B2)
CI = (lamda_max - n) / (n - 1)
CR = CI / RI[n - 1]

print(W_B2)
print(CR < 0.1)
print("CR:", CR)

[0.49151806 0.3058879  0.07771583 0.12487821]
True
CR: 0.017910309477395227


In [22]:
# B3 -- C
#B = [
#    [1, 1/3, 1/4],
#    [3, 1, 1/2],
#    [4, 2, 1],
#]
B = [
    [1, 1/2, 1/5, 1/4],
    [2, 1, 1/4, 1/3],
    [5, 4, 1, 3],
    [4, 3, 1/3, 1],
]
# Step 1.
M = np.multiply.reduce(B,axis=1)

# Step 2.
n = np.shape(M)[0]
W_AVG = pow(M, 1/n)

# Step 3.
W_B3 = W_AVG / np.sum(W_AVG)

# Step 4.
lamda_max = (1/n) * np.sum( (np.matmul(B, W_B3) ) / W_B3)
CI = (lamda_max - n) / (n - 1)
CR = CI / RI[n - 1]

print(W_B3)
print(CR < 0.1)
print("CR:", CR)

[0.07597233 0.12207666 0.53175094 0.27020007]
True
CR: 0.042313483958375836


In [23]:
# B4 -- C
#B = [
#    [1, 2, 3],
#    [1/2, 1, 2],
#    [1/3, 1/2, 1],
#]
#B = [
#    [1, 1/2, 3, 3, 3, 3],
#    [2, 1, 3, 3, 3, 3],
#    [1/3, 1/3, 1, 2, 2, 3],
#    [1/3, 1/3, 1/2, 1, 2, 2],
#    [1/3, 1/3, 1/2, 1/2, 1, 2],
#    [1/3, 1/3, 1/3, 1/2, 1/2, 1],
#]
B = [
    [1, 1/2, 3, 3],
    [2, 1, 3, 3],
    [1/3, 1/3, 1, 2],
    [1/3, 1/3, 1/2, 1],
]
# Step 1.
M = np.multiply.reduce(B,axis=1)

# Step 2.
n = np.shape(M)[0]
W_AVG = pow(M, 1/n)

# Step 3.
W_B4 = W_AVG / np.sum(W_AVG)

# Step 4.
lamda_max = (1/n) * np.sum( (np.matmul(B, W_B4) ) / W_B4)
CI = (lamda_max - n) / (n - 1)
CR = CI / RI[n - 1]

print(W_B4)
print(CR < 0.1)
print("CR:", CR)

[0.31066017 0.43933983 0.14644661 0.10355339]
True
CR: 0.04493346057764516


In [24]:
print(W_A[0] * W_B1)
print(W_A[1] * W_B2)
print(W_A[2] * W_B3)
print(W_A[3] * W_B4)

[0.18450008 0.08135164 0.11224327 0.02454451 0.0430848 ]
[0.13998064 0.08711457 0.02213288 0.03556437]
[0.01249175 0.02007246 0.08743315 0.04442765]
[0.03263741 0.04615626 0.01538542 0.01087914]


In [25]:
print(np.sum(W_A[0] * W_B1))
print(np.sum(W_A[1] * W_B2))
print(np.sum(W_A[2] * W_B3))
print(np.sum(W_A[3] * W_B4))

0.4457242996002299
0.2847924676245665
0.16442500784622127
0.10505822492898235


In [26]:
0.4723430910541628 + 0.28542515888449904 + 0.16971481487311418 + 0.07251693518822402

1.0