In [6]:
import numpy as np

a = np.array([1,2,3])
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a.shape)
print(b.shape)
print(a.dtype)

b[1, 1] = 10
print(b)

(3,)
(3, 3)
int64
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]


In [20]:
# dtype
persontype = np.dtype({'names':['name', 'age', 'chinese', 'math', 'english'], 'formats':['S32','i', 'i', 'i', 'f']})
people = np.array([("a", 12, 100, 100, 100), ("b", 13, 99, 99, 99), ("c123", 14, 98, 98, 98)], dtype=persontype)
print(people)
print(people[:]['age'])
print(people[:]['math'])
print(np.mean(people[:]['age']))
print(np.mean(people[:]['math']))
print(np.mean(people[:]['chinese']))

[(b'a', 12, 100, 100, 100.) (b'b', 13,  99,  99,  99.)
 (b'c123', 14,  98,  98,  98.)]
[12 13 14]
[100  99  98]
13.0
99.0
99.0


In [33]:
# arange/linspace
x1 = np.arange(1, 11, 2)
x2 = np.linspace(1, 9, 5)
print(x1)
print(x2)
print(np.add(x1, x2))
print(np.subtract(x1, x2))
print(np.multiply(x1, x2))
print(np.divide(x1, x2))
print(np.power(x1, 2))
print(np.remainder(x1, 3))

[1 3 5 7 9]
[1. 3. 5. 7. 9.]
[ 2.  6. 10. 14. 18.]
[0. 0. 0. 0. 0.]
[ 1.  9. 25. 49. 81.]
[1. 1. 1. 1. 1.]
[ 1  9 25 49 81]
[1 0 2 1 0]


In [41]:
# amax/amin
print(np.amax(a))
print(b)
print(np.amin(b))
print(np.amin(b,0))
print(np.amin(b,1))
print(np.amax(b))
print(np.amax(b,0))
print(np.amax(b,1))

3
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]
1
[1 2 3]
[1 4 7]
10
[ 7 10  9]
[ 3 10  9]


In [44]:
# ptp
print(np.ptp(b))
print(np.ptp(b,0))
print(np.ptp(b,1))

9
[6 8 6]
[2 6 2]


In [57]:
# percentile ???
print(b)
print(np.percentile(b, 98))
print(np.sum(b))
print(np.sum(b)*0.98)

[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]
9.84
50
49.0


In [60]:
# median/mean
print(b)

#median
print(np.median(b))
print(np.median(b, 0))
print(np.median(b, 1))

# mean
print(np.mean(b))
print(np.mean(b, 0))
print(np.mean(b, 1))

[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]
6.0
[4. 8. 6.]
[2. 6. 8.]
5.555555555555555
[4.         6.66666667 6.        ]
[2.         6.66666667 8.        ]


In [62]:
#average
a = wts = [1,2,3,4]
print(np.average(a))
print(np.average(a, weights=wts))

2.5
3.0


In [64]:
# std/var

#方差的计算是指每个数值与平均值之差的平方求和的平均值，
#即 mean((x - x.mean())** 2)。
#标准差是方差的算术平方根。
#在数学意义上，代表的是一组数据离平均值的分散程度。
a = [1,2,3,4]
print(np.std(a))
print(np.var(a))

1.118033988749895
1.25


In [70]:
# sort
a = [[4,3,2], [2,4,1]]
print(a)
print(np.sort(a))
print(np.sort(a, axis=None))
print(np.sort(a, axis=0))
print(np.sort(a, axis=1))

[[4, 3, 2], [2, 4, 1]]
[[2 3 4]
 [1 2 4]]
[1 2 2 3 4 4]
[[2 3 1]
 [4 4 2]]
[[2 3 4]
 [1 2 4]]


In [104]:
# assigment
persontype = np.dtype({'names':['name', 'chinese', 'english', 'math', 'total'], 'formats':['U32','i', 'i', 'i', 'i']})
people = np.array([("张飞", 66, 65, 30, 0), ("关羽", 95, 85, 98, 0), ("赵云", 93, 92, 96, 0), ("黄忠", 90, 88, 77, 0), ("典韦", 80, 90, 90, 0)], dtype=persontype)
print(people)

#mean
print("mean:")
print(np.mean(people[:]['chinese']))
print(np.mean(people[:]['english']))
print(np.mean(people[:]['math']))

#min
print("min:")
print(np.amin(people[:]['chinese']))
print(np.amin(people[:]['english']))
print(np.amin(people[:]['math']))

#max
print("max:")
print(np.amax(people[:]['chinese']))
print(np.amax(people[:]['english']))
print(np.amax(people[:]['math']))

#var
print("var:")
print(np.var(people[:]['chinese']))
print(np.var(people[:]['english']))
print(np.var(people[:]['math']))

#std
print("std:")
print(np.std(people[:]['chinese']))
print(np.std(people[:]['english']))
print(np.std(people[:]['math']))

#sort
print("sort:")
print(np.sort(people[:]['chinese']))
print(np.sort(people[:]['english']))
print(np.sort(people[:]['math']))

#print("total sort:", np.sort(np.sum(people[1:3],1)))

people[:]['total'] = people[:]['chinese']+people[:]['english']+people[:]['math']
print(np.sort(people, order='total'))

[('张飞', 66, 65, 30, 0) ('关羽', 95, 85, 98, 0) ('赵云', 93, 92, 96, 0)
 ('黄忠', 90, 88, 77, 0) ('典韦', 80, 90, 90, 0)]
mean:
84.8
84.0
78.2
min:
66
65
30
max:
95
92
98
var:
114.96000000000001
95.6
634.56
std:
10.721940122944169
9.777525249264253
25.19047439013406
sort:
[66 80 90 93 95]
[65 85 88 90 92]
[30 77 90 96 98]
[('张飞', 66, 65, 30, 161) ('黄忠', 90, 88, 77, 255) ('典韦', 80, 90, 90, 260)
 ('关羽', 95, 85, 98, 278) ('赵云', 93, 92, 96, 281)]
